# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9be66ccfaaf5d49db0802a1167fb79a42883e9e5677053c149b25932bce3278190fd29cb58e37434618e9fcac14823454a68d9a2b484ac061fb50a44eed103f5

test:
  secret_key_base: 2ba5589b4414f87ab73d7736cc645ed126d4df9d01a0319f8e7e928e4f08a4d0b54060a7e5c0ec615814701065e5fb73e37a0bdf9d5034063745c4f568d502af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
